[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "cluedo"
version = "0.1.0"
dependencies = [
    "pygame",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
